name: Regression Tests
on: [push, pull_request]

jobs:
  test:
    name: Tox (pytest) - ${{ matrix.os }} / ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-22.04]
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Verilator
      run: |
        sudo apt update -y
        sudo apt-get install git help2man perl python3 make autoconf g++ flex bison ccache -fy
        sudo apt-get install libunwind-dev libgoogle-perftools-dev numactl perl-doc -fy
        sudo apt-get install libfl2 -fy # Ubuntu only (ignore if gives error)
        sudo apt-get install libfl-dev -fy # Ubuntu only (ignore if gives error)
        sudo apt-get install zlib1g zlib1g-dev -fy # Ubuntu only (ignore if gives error)

        git clone https://github.com/verilator/verilator.git
        cd verilator
        git checkout stable
        autoconf
        ./configure
        make -j $(nproc)
        sudo make install
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Test with tox
      run: tox

    - name: Generate coverage
      run: make cov RUN_CMD=

    - name: Upload coverage
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV }} # not required for public repos
        files: ./coverage.info
        fail_ci_if_error: true
        verbose: true
